server.port: 7778

spring:
  application:
    name: customer-service
  config:
    activate:
      on-profile: default
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  jpa:
    database: POSTGRESQL
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=cinema&binaryTransfer=true&reWriteBatchedInserts=true
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    platform: postgres
    initialization-mode: always

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888