/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package book.my.show.kafka.booking.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum BookingApprovalStatus implements org.apache.avro.generic.GenericEnumSymbol<BookingApprovalStatus> {
  APPROVED, REJECTED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"BookingApprovalStatus\",\"namespace\":\"book.my.show.kafka.booking.avro.model\",\"symbols\":[\"APPROVED\",\"REJECTED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
